---

REF:
    T2Tv1_1: /net/eichler/vol26/projects/chm13_t2t/nobackups/assemblies/chm13_v1.1_plus38Y.fasta

ASM:
    Chimp_H1: /net/eichler/vol26/projects/primate_sv/nobackups/NHP_HiFi_assemblies_h1_h2/Chimpanzee_h1.fasta
    Chimp_H2: /net/eichler/vol26/projects/primate_sv/nobackups/NHP_HiFi_assemblies_h1_h2/Chimpanzee_h2.fasta 


